### PR TITLE
Fix read-only property assignment

### PR DESCRIPTION
**Pull request by diongerritzen**
When calling `onegini.fetch()` while using strict mode, the `event.target = this;` assignment causes an exception in the Cordova `callbackFromNative` function.

### CODE REVIEW

**Comment by robertszuba** [comment]
Hi @diongerritzen 
Thanks for the PR. Could you explain which versions of the plugin you're using? If it's the latest 4.1.0 then we need to merge it to our develop branch. If it's a fix for older version of the plugin, we'll merge it to a proper hotfix branches and then the develop.

**Comment by diongerritzen** [comment]
We are personally using version 3.0.2, but we noticed the same code is still present in 4.1.0. Of course I should've made the pull request for develop, my bad.

**Comment by diongerritzen** [comment]
I think I messed up this pull request... I'll make a new one, properly from the develop branch this time.

**Comment by diongerritzen** [comment]
Made a new pull request: #86

**Pull request closed without merging**
